version: 0.2
env:
  variables:
    ECR_REPO_NAME: java-demo-git
    cluster_name: pmg-automated6
    #AWS_ACCOUNT_ID: 252007810724
    #AWS_REGION: ap-south-1

  secret-manager:
    DOCKERHUB_TOKEN: java-cicd-pmg:token
    DOCKERHUB_USER: java-cicd-pmg:user
phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
        - wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
        - echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
        - sudo apt update && sudo apt install terraform
        - echo "terraform installed successfully..."
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/m6r4f3q8
      - ECR_MAIN_URI="252007810724.dkr.ecr.ap-south-1.amazonaws.com"
      - ECR_IMAGE_URI="${ECR_MAIN_URI}/${ECR_REPO_NAME}:latest"
      - echo "Login successfull..."
      # - echo "creating a ecr repo"
      # - aws cloudformation create-stack --stack-name ecrstack --template-body ecr.yaml --region ap-south-1
      
  build:
    commands: 
      - echo "creating eks cluster ..."
      - terraform init
      - terraform apply -auto-approve
      - echo "setting the eks context aws-auth configmap..."
      - kubectl config get-contexts
      - echo "Updating aws-auth ConfigMap for EKS cluster"
      - aws eks update-kubeconfig --name pmg-automated6 --region ap-south-1
      - kubectl apply -f aws-auth-configmap.yaml 
      - echo "eks authentication configmap set successfully... "

      - echo "building docker image..."
      - docker build -t java-demo-git .
      - docker tag java-demo-git:latest public.ecr.aws/m6r4f3q8/java-demo-git:latest
      - echo "pushing image to ECR"
      - docker push public.ecr.aws/m6r4f3q8/java-demo-git:latest
      - echo "successfully pushed image... check ECR repo"
      
  post_build:
    commands:
      - echo '[{"name":"java-demo-git","imageUri":"%s"}]' ${ECR_IMAGE_URI} > imagedefinitions.json
      - echo "artifacts uploading done..."
      - kubectl apply -f $CODEBUILD_SRC_DIR/deployment.yaml
      - kubectl get nodes
      - kubectl get deployments
      - kubectl get svc 
      - kubectl get ns 
      - kubectl describe service java-app-service
artifacts:
  files:
    - imagedefinitions.json
