version: 0.2
env:
  variables:
    ECR_REPO_NAME: java-demo-git
    AWS_ACCOUNT_ID: 252007810724
    AWS_REGION: ap-south-1
  secret-manager:
    DOCKERHUB_TOKEN: java-cicd:DOCKERHUB_TOKEN
    DOCKERHUB_USER: java-cicd:DOCKERHUB_USER
phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr-public get-login-password --region us-east-1 | docker login -u AWS --password-stdin public.ecr.aws
      - echo "logging to ECR"
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 252007810724.dkr.ecr.ap-south-1.amazonaws.com
      - ECR_MAIN_URI="252007810724.dkr.ecr.us-east-1.amazonaws.com"
      - aws ecr get-login-password --region us-east-1 | docker login -u AWS --password-stdin ${ECR_MAIN_URI}
      - echo "Login successfull..."
  build:
    commands: 
      - ECR_IMAGE_URI="252007810724.dkr.ecr.ap-south-1.amazonaws.com/$ECR_REPO_NAME:latest"
      - echo "building docker image..."
      - docker build -t java-demo-git .
      - docker tag java-demo-git:latest 252007810724.dkr.ecr.ap-south-1.amazonaws.com/java-demo-git:latest
  post_build:
    commands:
      - echo "pushing image to ECR"
      - docker push 252007810724.dkr.ecr.ap-south-1.amazonaws.com/java-demo-git:latest
      - echo "successfully pushed image... check ECR repo"
      - echo '[{"name":"java-demo-git","imageUri":"%s"}]' ${ECR_IMAGE_URI} > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
