version: 0.2
env:
  variables:
    ECR_REPO_NAME: java-demo-git
  secret-manager:
    DOCKERHUB_TOKEN: java-cicd:DOCKERHUB_TOKEN
    DOCKERHUB_USER: java-cicd:DOCKERHUB_USER
phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - mvn package
      # - mvn clean install
      # - mvn package 
      # - mkdir -p pkg
      # - mv target/demo.war pkg/demo.war
      - echo "Logging in to Amazon ECR..."
      - aws ecr-public get-login-password --region us-east-1 | docker login -u AWS --password-stdin public.ecr.aws
      # - ECR_MAIN_URI= "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"
      - ECR_MAIN_URI="252007810724.dkr.ecr.ap-south-1.amazonaws.com"
      - aws ecr get-login-password --region us-east-1 | docker login -u AWS --password-stdin 252007810724.dkr.ecr.us-east-1.amazonaws.com
      - ECR_IMAGE_URI="252007810724.dkr.ecr.us-east-1.amazonaws.com/${ECR_REPO_NAME}:latest"
      - echo "building docker image..."
      - docker build -t java-demo-git:latest .
      - docker tag demo-java:latest ${ECR_IMAGE_URI}
      - echo "pushing image to the ecr..."
      - docker push ${ECR_IMAGE_URI}
      - echo "image pushed to the ecr"
      - echo '[{"name":"java-app","imageUri":"%s"}]' ${ECR_IMAGE_URI} > imagedefinitions.json
   # build:
  #   commands:
  #     - docker build -t demo-java . 
  #     #- docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
  #     #- sudo docker tag demo-java:latest ${ECR_IMAGE_URI}
  # post_build:
  #   commands:
  #     - echo "Pushing the Docker image to Amazon ECR..."
  #     - docker push 252007810724.dkr.ecr.us-east-1.amazonaws.com/ECR_REPO_NAME:latest
  #     #- sudo docker push ${ECR_IMAGE_URI}
  #     - echo '[{"name":"java-app","imageUri":"%s"}]' ${ECR_IMAGE_URI} > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
