version: 0.2
env:
  variables:
    ECR_REPO_NAME: java-demo-git
phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - mvn clean install
      - echo "Logging in to Amazon ECR..."
      - aws ecr-public get-login-password --region us-east-1 | docker login -u AWS --password-stdin public.ecr.aws
      - ECR_MAIN_URI="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"
      - aws ecr get-login-password --region ${AWS_REGION} | docker login -u AWS --password-stdin ${ECR_MAIN_URI}
      - sudo service docker  start
      - ECR_IMAGE_URI="${ECR_MAIN_URI}/${ECR_REPO_NAME}:latest"
      - docker build -t java-tomcat:latest .
      - docker tag java-tomcat:latest ${ECR_IMAGE_URI}
  post_build:
    commands:
      - echo "Pushing the Docker image to Amazon ECR..."
      - docker push ${ECR_IMAGE_URI}
artifacts:
  files:
    - imagedefinitions.json
