apiVersion: v1
data:
  mapRoles: |
    - rolearn: *
      username: eks-cluster-role
      groups:
        - system:masters
  mapUsers: |
    - userarn: *
      username: cluster-user
      groups:
        - system:masters
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
