AWSTemplateFormatVersion: 2010-09-09
Parameters:
  repositoryName:
    Type: String
    Default: motadata-image-repo

Resources:
  MyRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref repositoryName

Outputs:
  Arn:
    Value: !GetAtt MyRepository.Arn
