AWSTemplateFormatVersion: 2010-09-09
Parameters:
  repositoryName:
    Type: String
    Default: motadata-image-repo
  registryId:
    Type: String

Resources:
  MyRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref repositoryName
      # ImageScanningConfiguration:
      #   scanOnPush: true
Outputs:
  Arn:
    Value: !GetAtt MyRepository.Arn
