AWSTemplateFormatVersion: 2010-09-09
Parameters:
  repositoryName:
    Type: String
    Default: java-demo-git11
Resources:
  myRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref repositoryName

Outputs:
  Arn:
    Value: !GetAtt myRepository.Arn
